# /**/send_obstacles:
#   ros__parameters:
#     n_obstacles: 5 # Number of RANDOM obstacles to be spawned
#     no_cylinders: true # If true, no cylinders will be spawned
#     no_boxes: false # If true, no boxes will be spawned
#     max_size: 1.0 # Maximum size of the random obstacles
#     min_size: 0.5 # Minimum size of the random obstacles
#     vect_type: [] #["cylinder", "box", "box"]     # Type of the obstacles to be spawned, either "cylinder" or "box"
#     vect_x: [] #[8.0, 2.0, -2.0]                  # X position of the obstacles
#     vect_y: [] #[8.0, 2.0, -2.0]                  # Y position of the obstacles
#     vect_yaw: [] #[0.0, 0.0, 0.0]                 # Yaw of the obstacles
#     vect_dim_x: [] #[0.5, 1.0, 1.0]               # X dimension of the obstacles
#     vect_dim_y: [] #[0.5, 1.0, 1.0]               # Y dimension of the obstacles
#     # If vect_* are empty lists or not defined, then only random obstacles will be spawned

# /**/send_gates:
#   ros__parameters:
#     use_namespace: false # If true, the gates will be spawned one for each Shelfino. Not yet implemented
#     x: [0.0] # X position of the gate(s)
#     y: [0.0] # Y position of the gate(s)
#     yaw: [0.0] # Yaw of the gate(s)
#     # Values of x and y different from 0.0 will spawn the gates in the given position

# /**/send_victims:
#   ros__parameters:
#     victims_activated: true # If true, the victims will be spawned
#     n_victims: 4 # Number of RANDOM victims to be spawned
#     min_weight: 10 # Minimum weight of the victims
#     max_weight: 500 # Maximum weight of the victims
#     vect_x: [] # X position of the victims
#     vect_y: [] # Y position of the victims
#     vect_weight: [] # Weight of the victims
#     victims_timeout: 0 # Time given to collect the victims and reach the gate in seconds. If 0, the simulation will choose one.
#     # If vect_* are empty lists or not defined, then only random victims will be spawned

/**:
  ros__parameters:
    use_sim_time: true
    map: "plane_2" # Maps can be "test_world" or "plane_2"
    world_frame: "map"
    init_names: ["shelfino1", "pollo"] # Names of the robots to be spawned
    init_rand: [false, false] # If true, the robots will be spawned in random positions
    init_x: [9.3, 14.24] # X position of the robots
    init_y: [1.2, 5.56] # Y position of the robots
    init_yaw: [0.65, -2.37] # Yaw of the robots

    # init_names: ["shelfino1"] # Names of the robots to be spawned
    # init_rand: [false] # If true, the robots will be spawned in random positions
    # init_x: [5.0] # X position of the robots
    # init_y: [4.5] # Y position of the robots
    # init_yaw: [0.0] # Yaw of the robots

    server:
      voxel_size: 0.05 #meters
      hz: 1 #update rate of the cluster
      maximum_count_per_voxel: 250 #number of point per voxel
      minimum_percentage: 0.1 # ... of the maximum detected to be considered when we are finding the voxels to analyze again
      voxel_estimate: "voxel_estimate_out"
      threshold_count_per_voxel: 30
      pcl_topic_in: "cluster_pcl"

    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: transient_local
          history: keep_last
          reliability: reliable
          
    topics:
      filtered_pcl: "filtered_pcl"
      raw_pcl: "f_camera/points"
      cluster_pose: "c_position"
      cluster_pcl: "cluster_pcl"
      positions_to_explore_topic_vis: "positions_to_explore_vis"
      cluster_centroid: "median" # "median" and "centroid"  are usable values
      

    pcl_filter_params:
      cluster_tolerance: .05
      plane_distance_treshold: 0.05

    shelfino_additions:
      max_camera_depth: 8.0
