<?xml version="1.0" ?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>dist_project</name>
  <version>1.0.0</version>
  <description>
    Package containing the launch files for the different tasks:
    - Multi-agent path finding: mapf.launch.py
    - Victims rescue: victims.launch.py
    - Purseur evader: pv.launch.py
  </description>
  <maintainer email="emmanuele.coppola@studenti.unitn.it">emmanuele</maintainer>
  <!-- <maintainer email="placido.falqueto@unitn.it">placido</maintainer> -->
  <license>Apache 2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>


  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>


  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>pcl_conversions</depend>
  <depend>pcl_transforms</depend>

  <depend>pcl_1.12</depend>
  <depend>visualization_msgs</depend>
  <depend>vision_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>tf2</depend>
  <depend>pcl_ros</depend>
  <depend>tf2_eigen</depend>


  <depend>shelfino_gazebo</depend>
  <depend>shelfino_description</depend>
  <depend>shelfino_navigation</depend>
  <!-- <depend>evader</depend> -->
  <depend>map_pkg</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
